# Merge Datasets

This is the only file that needs to be executed in order to be able to work with the analysis notebooks.<br>
It executes the Weather Scraping, Taxi Data Preparation, and Weather Data Preparation.

### Imports

In [54]:
import pandas as pd

### Run Weather Scraping

In [ ]:
%%capture
#run weather scraping, about 1min
%run weather_scraping.ipynb

### Run Data Preparations

In [55]:
%%capture
#run taxi trip preparation, about 5min
%run taxi_data_preparation.ipynb

In [56]:
%%capture
#run weahter data preparation, about 1min
%run weather_data_preparation.ipynb

In [57]:
#import the prepared datasets
taxi_trips = pd.read_csv('data/prepared/taxi_trips.csv')
weather_data = pd.read_csv('data/prepared/weather_data_2022.csv')

### Merge Datasets

In [58]:
#merge taxi trips on start time with weather data on date time
taxi_weather = pd.merge(taxi_trips, weather_data, left_on='start_time', right_on='date_time', how='left')
#seconds time not needed
taxi_weather = taxi_weather.drop('date_time', axis=1)
taxi_weather

,trip_id,taxi_id,start_time,end_time,minutes,miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,temperature,wind_speed,precip,condition
0,bcfa19f2539021c054809d4c3993d226996ae095,368ce5511598af2cc07efdb68067d381174fdac1d47a28...,2022-01-01 00:00:00,2022-01-01 00:00:00,2.53,0.10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy
1,2aba69ff015f9ea8e7bff43cab7eddb228f34a12,449fa4909552757130d09d98ebc7770e2dd94579036b0e...,2022-01-01 00:00:00,2022-01-01 00:30:00,39.33,17.44,NaN,NaN,NaN,8.0,...,NaN,NaN,NaN,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),33,21.0,0.0,Light Snow / Windy
2,54d812a0b88f8f9707825261014b3563a0a60ace,f98ae5e71fdda8806710af321dce58002146886c013f41...,2022-01-01 00:00:00,2022-01-01 00:00:00,8.93,4.83,NaN,NaN,28.0,22.0,...,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.922761,-87.699155,POINT (-87.6991553432 41.9227606205),33,21.0,0.0,Light Snow / Windy
3,040caea96573c5743668b138011bc157c7825e86,b9a58663518c48b09e83f462ca25ee0d702a2e4bc12199...,2022-01-01 00:00:00,2022-01-01 00:15:00,20.93,13.29,NaN,NaN,76.0,NaN,...,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy
4,0f0c856e620e6b4dfd2bb1e921d966dd179eeca1,b21050ab3ad3d0972fd6378f6bf4d0251a8a7af42e6e0e...,2022-01-01 00:00:00,2022-01-01 00:00:00,0.55,0.17,NaN,NaN,3.0,3.0,...,41.965812,-87.655879,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),33,21.0,0.0,Light Snow / Windy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,ae3d90108a96c6492a6255f7fc6b85c8e7e0d12c,2eda36427e0a5394e90d77488294cd75e2fd87f04acb02...,2022-12-31 23:45:00,2022-12-31 23:45:00,3.27,0.57,NaN,NaN,6.0,6.0,...,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),37,6.0,0.0,Cloudy
5389590,ad84bc072bb580f059a1c2b71a808b21e28a28fb,ef63da921ed08ceb44e590dbb76b0505f1300167c24876...,2022-12-31 23:45:00,2022-12-31 23:45:00,5.90,0.85,1.703184e+10,1.703132e+10,32.0,32.0,...,41.880994,-87.632746,POINT (-87.6327464887 41.8809944707),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),37,6.0,0.0,Cloudy
5389591,b13dcd7ede0551d30944feab189891fdca8873b6,6201cd8256e26b0ef547ca53db3aaac4d23fc7d02e4c9f...,2022-12-31 23:45:00,2022-12-31 23:45:00,1.72,0.31,NaN,NaN,3.0,3.0,...,41.965812,-87.655879,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),37,6.0,0.0,Cloudy
5389592,d35a54c3d20c5275718151191d6cbd3624640931,e87c704a9b1b4c7e9036508cc65d110d38bb2f8d12414b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.33,1.58,NaN,NaN,7.0,7.0,...,41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),37,6.0,0.0,Cloudy
5389593,f5ba11ba1d2f0dd11c598d05481947e19c8e1a17,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.98,1.85,NaN,NaN,32.0,28.0,...,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),41.874005,-87.663518,POINT (-87.6635175498 41.874005383),37,6.0,0.0,Cloudy

In [59]:
#export merged taxi-weather dataset
taxi_weather.to_csv('data/prepared/taxi_weather.csv', index=False)