In [1]:
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import numpy as np

In [2]:
!pip install -U scikit-fuzzy

^C

In [2]:
# Import Weather Datset
df = pd.read_csv('taxi_weather.csv')
df

,trip_id,taxi_id,start_time,end_time,minutes,miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,temperature,wind_speed,precip,condition
0,bcfa19f2539021c054809d4c3993d226996ae095,368ce5511598af2cc07efdb68067d381174fdac1d47a28...,2022-01-01 00:00:00,2022-01-01 00:00:00,2.53,0.10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy
1,2aba69ff015f9ea8e7bff43cab7eddb228f34a12,449fa4909552757130d09d98ebc7770e2dd94579036b0e...,2022-01-01 00:00:00,2022-01-01 00:30:00,39.33,17.44,NaN,NaN,NaN,8.0,...,NaN,NaN,NaN,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),33,21.0,0.0,Light Snow / Windy
2,54d812a0b88f8f9707825261014b3563a0a60ace,f98ae5e71fdda8806710af321dce58002146886c013f41...,2022-01-01 00:00:00,2022-01-01 00:00:00,8.93,4.83,NaN,NaN,28.0,22.0,...,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.922761,-87.699155,POINT (-87.6991553432 41.9227606205),33,21.0,0.0,Light Snow / Windy
3,040caea96573c5743668b138011bc157c7825e86,b9a58663518c48b09e83f462ca25ee0d702a2e4bc12199...,2022-01-01 00:00:00,2022-01-01 00:15:00,20.93,13.29,NaN,NaN,76.0,NaN,...,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy
4,0f0c856e620e6b4dfd2bb1e921d966dd179eeca1,b21050ab3ad3d0972fd6378f6bf4d0251a8a7af42e6e0e...,2022-01-01 00:00:00,2022-01-01 00:00:00,0.55,0.17,NaN,NaN,3.0,3.0,...,41.965812,-87.655879,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),33,21.0,0.0,Light Snow / Windy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,ae3d90108a96c6492a6255f7fc6b85c8e7e0d12c,2eda36427e0a5394e90d77488294cd75e2fd87f04acb02...,2022-12-31 23:45:00,2022-12-31 23:45:00,3.27,0.57,NaN,NaN,6.0,6.0,...,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),37,6.0,0.0,Cloudy
5389590,ad84bc072bb580f059a1c2b71a808b21e28a28fb,ef63da921ed08ceb44e590dbb76b0505f1300167c24876...,2022-12-31 23:45:00,2022-12-31 23:45:00,5.90,0.85,1.703184e+10,1.703132e+10,32.0,32.0,...,41.880994,-87.632746,POINT (-87.6327464887 41.8809944707),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),37,6.0,0.0,Cloudy
5389591,b13dcd7ede0551d30944feab189891fdca8873b6,6201cd8256e26b0ef547ca53db3aaac4d23fc7d02e4c9f...,2022-12-31 23:45:00,2022-12-31 23:45:00,1.72,0.31,NaN,NaN,3.0,3.0,...,41.965812,-87.655879,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),37,6.0,0.0,Cloudy
5389592,d35a54c3d20c5275718151191d6cbd3624640931,e87c704a9b1b4c7e9036508cc65d110d38bb2f8d12414b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.33,1.58,NaN,NaN,7.0,7.0,...,41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),37,6.0,0.0,Cloudy
5389593,f5ba11ba1d2f0dd11c598d05481947e19c8e1a17,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.98,1.85,NaN,NaN,32.0,28.0,...,41.878866,-87.625192,POINT (-87.6251921424 41.8788655841),41.874005,-87.663518,POINT (-87.6635175498 41.874005383),37,6.0,0.0,Cloudy

In [3]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
#payment_type'     company  condition
# Using .fit_transform function to fit label
# encoder and return encoded label
#label = le.fit_transform(df['condition'])
label = le.fit_transform(df['company'])

# printing label
label
# removing the column 'Purchased' from df
# as it is of no use now.
df.drop("company", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
df["company"] = label
 
# printing Dataframe
df

,trip_id,taxi_id,start_time,end_time,minutes,miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,temperature,wind_speed,precip,condition,company
0,bcfa19f2539021c054809d4c3993d226996ae095,368ce5511598af2cc07efdb68067d381174fdac1d47a28...,2022-01-01 00:00:00,2022-01-01 00:00:00,2.53,0.10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy,23
1,2aba69ff015f9ea8e7bff43cab7eddb228f34a12,449fa4909552757130d09d98ebc7770e2dd94579036b0e...,2022-01-01 00:00:00,2022-01-01 00:30:00,39.33,17.44,NaN,NaN,NaN,8.0,...,NaN,NaN,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),33,21.0,0.0,Light Snow / Windy,18
2,54d812a0b88f8f9707825261014b3563a0a60ace,f98ae5e71fdda8806710af321dce58002146886c013f41...,2022-01-01 00:00:00,2022-01-01 00:00:00,8.93,4.83,NaN,NaN,28.0,22.0,...,-87.663518,POINT (-87.6635175498 41.874005383),41.922761,-87.699155,POINT (-87.6991553432 41.9227606205),33,21.0,0.0,Light Snow / Windy,19
3,040caea96573c5743668b138011bc157c7825e86,b9a58663518c48b09e83f462ca25ee0d702a2e4bc12199...,2022-01-01 00:00:00,2022-01-01 00:15:00,20.93,13.29,NaN,NaN,76.0,NaN,...,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy,17
4,0f0c856e620e6b4dfd2bb1e921d966dd179eeca1,b21050ab3ad3d0972fd6378f6bf4d0251a8a7af42e6e0e...,2022-01-01 00:00:00,2022-01-01 00:00:00,0.55,0.17,NaN,NaN,3.0,3.0,...,-87.655879,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),33,21.0,0.0,Light Snow / Windy,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,ae3d90108a96c6492a6255f7fc6b85c8e7e0d12c,2eda36427e0a5394e90d77488294cd75e2fd87f04acb02...,2022-12-31 23:45:00,2022-12-31 23:45:00,3.27,0.57,NaN,NaN,6.0,6.0,...,-87.655998,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),37,6.0,0.0,Cloudy,31
5389590,ad84bc072bb580f059a1c2b71a808b21e28a28fb,ef63da921ed08ceb44e590dbb76b0505f1300167c24876...,2022-12-31 23:45:00,2022-12-31 23:45:00,5.90,0.85,1.703184e+10,1.703132e+10,32.0,32.0,...,-87.632746,POINT (-87.6327464887 41.8809944707),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),37,6.0,0.0,Cloudy,17
5389591,b13dcd7ede0551d30944feab189891fdca8873b6,6201cd8256e26b0ef547ca53db3aaac4d23fc7d02e4c9f...,2022-12-31 23:45:00,2022-12-31 23:45:00,1.72,0.31,NaN,NaN,3.0,3.0,...,-87.655879,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),37,6.0,0.0,Cloudy,31
5389592,d35a54c3d20c5275718151191d6cbd3624640931,e87c704a9b1b4c7e9036508cc65d110d38bb2f8d12414b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.33,1.58,NaN,NaN,7.0,7.0,...,-87.649489,POINT (-87.6494887289 41.9226862843),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),37,6.0,0.0,Cloudy,17
5389593,f5ba11ba1d2f0dd11c598d05481947e19c8e1a17,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.98,1.85,NaN,NaN,32.0,28.0,...,-87.625192,POINT (-87.6251921424 41.8788655841),41.874005,-87.663518,POINT (-87.6635175498 41.874005383),37,6.0,0.0,Cloudy,19

In [4]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
#payment_type'     company  condition
# Using .fit_transform function to fit label
# encoder and return encoded label
#label = le.fit_transform(df['condition'])
label = le.fit_transform(df['payment_type'])

# printing label
label
# removing the column 'Purchased' from df
# as it is of no use now.
df.drop("payment_type", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
df["payment_type"] = label
 
# printing Dataframe
df

,trip_id,taxi_id,start_time,end_time,minutes,miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,temperature,wind_speed,precip,condition,company,payment_type
0,bcfa19f2539021c054809d4c3993d226996ae095,368ce5511598af2cc07efdb68067d381174fdac1d47a28...,2022-01-01 00:00:00,2022-01-01 00:00:00,2.53,0.10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy,23,0
1,2aba69ff015f9ea8e7bff43cab7eddb228f34a12,449fa4909552757130d09d98ebc7770e2dd94579036b0e...,2022-01-01 00:00:00,2022-01-01 00:30:00,39.33,17.44,NaN,NaN,NaN,8.0,...,NaN,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),33,21.0,0.0,Light Snow / Windy,18,0
2,54d812a0b88f8f9707825261014b3563a0a60ace,f98ae5e71fdda8806710af321dce58002146886c013f41...,2022-01-01 00:00:00,2022-01-01 00:00:00,8.93,4.83,NaN,NaN,28.0,22.0,...,POINT (-87.6635175498 41.874005383),41.922761,-87.699155,POINT (-87.6991553432 41.9227606205),33,21.0,0.0,Light Snow / Windy,19,0
3,040caea96573c5743668b138011bc157c7825e86,b9a58663518c48b09e83f462ca25ee0d702a2e4bc12199...,2022-01-01 00:00:00,2022-01-01 00:15:00,20.93,13.29,NaN,NaN,76.0,NaN,...,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN,33,21.0,0.0,Light Snow / Windy,17,0
4,0f0c856e620e6b4dfd2bb1e921d966dd179eeca1,b21050ab3ad3d0972fd6378f6bf4d0251a8a7af42e6e0e...,2022-01-01 00:00:00,2022-01-01 00:00:00,0.55,0.17,NaN,NaN,3.0,3.0,...,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),33,21.0,0.0,Light Snow / Windy,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,ae3d90108a96c6492a6255f7fc6b85c8e7e0d12c,2eda36427e0a5394e90d77488294cd75e2fd87f04acb02...,2022-12-31 23:45:00,2022-12-31 23:45:00,3.27,0.57,NaN,NaN,6.0,6.0,...,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),37,6.0,0.0,Cloudy,31,1
5389590,ad84bc072bb580f059a1c2b71a808b21e28a28fb,ef63da921ed08ceb44e590dbb76b0505f1300167c24876...,2022-12-31 23:45:00,2022-12-31 23:45:00,5.90,0.85,1.703184e+10,1.703132e+10,32.0,32.0,...,POINT (-87.6327464887 41.8809944707),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),37,6.0,0.0,Cloudy,17,0
5389591,b13dcd7ede0551d30944feab189891fdca8873b6,6201cd8256e26b0ef547ca53db3aaac4d23fc7d02e4c9f...,2022-12-31 23:45:00,2022-12-31 23:45:00,1.72,0.31,NaN,NaN,3.0,3.0,...,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),37,6.0,0.0,Cloudy,31,0
5389592,d35a54c3d20c5275718151191d6cbd3624640931,e87c704a9b1b4c7e9036508cc65d110d38bb2f8d12414b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.33,1.58,NaN,NaN,7.0,7.0,...,POINT (-87.6494887289 41.9226862843),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),37,6.0,0.0,Cloudy,17,3
5389593,f5ba11ba1d2f0dd11c598d05481947e19c8e1a17,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.98,1.85,NaN,NaN,32.0,28.0,...,POINT (-87.6251921424 41.8788655841),41.874005,-87.663518,POINT (-87.6635175498 41.874005383),37,6.0,0.0,Cloudy,19,3

In [5]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
#payment_type'     company  condition
# Using .fit_transform function to fit label
# encoder and return encoded label
#label = le.fit_transform(df['condition'])
label = le.fit_transform(df['condition'])

# printing label
label
# removing the column 'Purchased' from df
# as it is of no use now.
df.drop("condition", axis=1, inplace=True)
 
# Appending the array to our dataFrame
# with column name 'Purchased'
df["condition"] = label
 
# printing Dataframe
df

,trip_id,taxi_id,start_time,end_time,minutes,miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location,temperature,wind_speed,precip,company,payment_type,condition
0,bcfa19f2539021c054809d4c3993d226996ae095,368ce5511598af2cc07efdb68067d381174fdac1d47a28...,2022-01-01 00:00:00,2022-01-01 00:00:00,2.53,0.10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,33,21.0,0.0,23,0,19
1,2aba69ff015f9ea8e7bff43cab7eddb228f34a12,449fa4909552757130d09d98ebc7770e2dd94579036b0e...,2022-01-01 00:00:00,2022-01-01 00:30:00,39.33,17.44,NaN,NaN,NaN,8.0,...,NaN,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),33,21.0,0.0,18,0,19
2,54d812a0b88f8f9707825261014b3563a0a60ace,f98ae5e71fdda8806710af321dce58002146886c013f41...,2022-01-01 00:00:00,2022-01-01 00:00:00,8.93,4.83,NaN,NaN,28.0,22.0,...,POINT (-87.6635175498 41.874005383),41.922761,-87.699155,POINT (-87.6991553432 41.9227606205),33,21.0,0.0,19,0,19
3,040caea96573c5743668b138011bc157c7825e86,b9a58663518c48b09e83f462ca25ee0d702a2e4bc12199...,2022-01-01 00:00:00,2022-01-01 00:15:00,20.93,13.29,NaN,NaN,76.0,NaN,...,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN,33,21.0,0.0,17,0,19
4,0f0c856e620e6b4dfd2bb1e921d966dd179eeca1,b21050ab3ad3d0972fd6378f6bf4d0251a8a7af42e6e0e...,2022-01-01 00:00:00,2022-01-01 00:00:00,0.55,0.17,NaN,NaN,3.0,3.0,...,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),33,21.0,0.0,18,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,ae3d90108a96c6492a6255f7fc6b85c8e7e0d12c,2eda36427e0a5394e90d77488294cd75e2fd87f04acb02...,2022-12-31 23:45:00,2022-12-31 23:45:00,3.27,0.57,NaN,NaN,6.0,6.0,...,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),37,6.0,0.0,31,1,2
5389590,ad84bc072bb580f059a1c2b71a808b21e28a28fb,ef63da921ed08ceb44e590dbb76b0505f1300167c24876...,2022-12-31 23:45:00,2022-12-31 23:45:00,5.90,0.85,1.703184e+10,1.703132e+10,32.0,32.0,...,POINT (-87.6327464887 41.8809944707),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),37,6.0,0.0,17,0,2
5389591,b13dcd7ede0551d30944feab189891fdca8873b6,6201cd8256e26b0ef547ca53db3aaac4d23fc7d02e4c9f...,2022-12-31 23:45:00,2022-12-31 23:45:00,1.72,0.31,NaN,NaN,3.0,3.0,...,POINT (-87.6558787862 41.96581197),41.965812,-87.655879,POINT (-87.6558787862 41.96581197),37,6.0,0.0,31,0,2
5389592,d35a54c3d20c5275718151191d6cbd3624640931,e87c704a9b1b4c7e9036508cc65d110d38bb2f8d12414b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.33,1.58,NaN,NaN,7.0,7.0,...,POINT (-87.6494887289 41.9226862843),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),37,6.0,0.0,17,3,2
5389593,f5ba11ba1d2f0dd11c598d05481947e19c8e1a17,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2022-12-31 23:45:00,2022-12-31 23:45:00,8.98,1.85,NaN,NaN,32.0,28.0,...,POINT (-87.6251921424 41.8788655841),41.874005,-87.663518,POINT (-87.6635175498 41.874005383),37,6.0,0.0,19,3,2

In [6]:
df=df.drop(columns='start_time')
df=df.drop(columns='end_time')
df=df.drop(columns='trip_id')
df=df.drop(columns='taxi_id')
df=df.drop(columns='pickup_census_tract')
df=df.drop(columns='dropoff_census_tract')

df=df.drop(columns='pickup_centroid_location')
df=df.drop(columns='dropoff_centroid_location')

df
#df.to_csv('data.csv', index=False)

,minutes,miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,temperature,wind_speed,precip,company,payment_type,condition
0,2.53,0.10,NaN,NaN,3.75,0.0,0.0,0.0,3.75,NaN,NaN,NaN,NaN,33,21.0,0.0,23,0,19
1,39.33,17.44,NaN,8.0,47.75,0.0,0.0,5.0,52.75,NaN,NaN,41.899602,-87.633308,33,21.0,0.0,18,0,19
2,8.93,4.83,28.0,22.0,14.75,0.0,0.0,0.0,14.75,41.874005,-87.663518,41.922761,-87.699155,33,21.0,0.0,19,0,19
3,20.93,13.29,76.0,NaN,34.00,0.0,0.0,6.0,40.00,41.980264,-87.913625,NaN,NaN,33,21.0,0.0,17,0,19
4,0.55,0.17,3.0,3.0,63.27,0.0,0.0,0.0,63.27,41.965812,-87.655879,41.965812,-87.655879,33,21.0,0.0,18,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,3.27,0.57,6.0,6.0,4.75,2.0,0.0,1.0,8.25,41.944227,-87.655998,41.944227,-87.655998,37,6.0,0.0,31,1,2
5389590,5.90,0.85,32.0,32.0,5.75,0.0,0.0,1.0,6.75,41.880994,-87.632746,41.884987,-87.620993,37,6.0,0.0,17,0,2
5389591,1.72,0.31,3.0,3.0,4.00,0.0,0.0,1.0,5.00,41.965812,-87.655879,41.965812,-87.655879,37,6.0,0.0,31,0,2
5389592,8.33,1.58,7.0,7.0,11.00,10.0,0.0,0.0,21.00,41.922686,-87.649489,41.922686,-87.649489,37,6.0,0.0,17,3,2
5389593,8.98,1.85,32.0,28.0,11.48,0.0,0.0,0.0,11.48,41.878866,-87.625192,41.874005,-87.663518,37,6.0,0.0,19,3,2

In [7]:
df.fillna(0)
df.replace(np.nan, 0)
df

,minutes,miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,temperature,wind_speed,precip,company,payment_type,condition
0,2.53,0.10,NaN,NaN,3.75,0.0,0.0,0.0,3.75,NaN,NaN,NaN,NaN,33,21.0,0.0,23,0,19
1,39.33,17.44,NaN,8.0,47.75,0.0,0.0,5.0,52.75,NaN,NaN,41.899602,-87.633308,33,21.0,0.0,18,0,19
2,8.93,4.83,28.0,22.0,14.75,0.0,0.0,0.0,14.75,41.874005,-87.663518,41.922761,-87.699155,33,21.0,0.0,19,0,19
3,20.93,13.29,76.0,NaN,34.00,0.0,0.0,6.0,40.00,41.980264,-87.913625,NaN,NaN,33,21.0,0.0,17,0,19
4,0.55,0.17,3.0,3.0,63.27,0.0,0.0,0.0,63.27,41.965812,-87.655879,41.965812,-87.655879,33,21.0,0.0,18,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,3.27,0.57,6.0,6.0,4.75,2.0,0.0,1.0,8.25,41.944227,-87.655998,41.944227,-87.655998,37,6.0,0.0,31,1,2
5389590,5.90,0.85,32.0,32.0,5.75,0.0,0.0,1.0,6.75,41.880994,-87.632746,41.884987,-87.620993,37,6.0,0.0,17,0,2
5389591,1.72,0.31,3.0,3.0,4.00,0.0,0.0,1.0,5.00,41.965812,-87.655879,41.965812,-87.655879,37,6.0,0.0,31,0,2
5389592,8.33,1.58,7.0,7.0,11.00,10.0,0.0,0.0,21.00,41.922686,-87.649489,41.922686,-87.649489,37,6.0,0.0,17,3,2
5389593,8.98,1.85,32.0,28.0,11.48,0.0,0.0,0.0,11.48,41.878866,-87.625192,41.874005,-87.663518,37,6.0,0.0,19,3,2

In [9]:
df['pickup_community_area'] = df['pickup_community_area'].replace(np.nan, 0)
df['dropoff_community_area'] = df['dropoff_community_area'].replace(np.nan, 0)
df['pickup_centroid_latitude'] = df['pickup_centroid_latitude'].replace(np.nan, 0)
df['pickup_centroid_longitude'] = df['pickup_centroid_longitude'].replace(np.nan, 0)
df['dropoff_centroid_latitude'] = df['dropoff_centroid_latitude'].replace(np.nan, 0)
df['dropoff_centroid_longitude'] = df['dropoff_centroid_longitude'].replace(np.nan, 0)
print (df.dtypes)
df.isnull().sum()

minutes                       float64
miles                         float64
pickup_community_area         float64
dropoff_community_area        float64
fare                          float64
tips                          float64
tolls                         float64
extras                        float64
total                         float64
pickup_centroid_latitude      float64
pickup_centroid_longitude     float64
dropoff_centroid_latitude     float64
dropoff_centroid_longitude    float64
temperature                     int64
wind_speed                    float64
precip                        float64
company                         int32
payment_type                    int32
condition                       int32
dtype: object

minutes                       0
miles                         0
pickup_community_area         0
dropoff_community_area        0
fare                          0
tips                          0
tolls                         0
extras                        0
total                         0
pickup_centroid_latitude      0
pickup_centroid_longitude     0
dropoff_centroid_latitude     0
dropoff_centroid_longitude    0
temperature                   0
wind_speed                    0
precip                        0
company                       0
payment_type                  0
condition                     0
dtype: int64

In [10]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=19).fit(df)
# 建立模型，K=19

df['cluster'] = km.labels_
#df.sort_values('cluster')
df.to_csv('cluster.csv', index=False)

KeyboardInterrupt:

In [71]:
import numpy as np
from sklearn.mixture import GaussianMixture
df=df.drop(columns='cluster')
gmm = GaussianMixture(n_components=4)
gmm.fit(df)
labels = gmm.predict(df)
df['cluster']=labels 
print(labels)
df.to_csv('cluster_gmm.csv', index=False)

[3 0 1 ... 1 2 1]

In [72]:
df

,minutes,miles,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,total,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,temperature,wind_speed,precip,condition,company,cluster
0,2.53,0.10,0.0,0.0,3.75,0.0,0.0,0.0,3.75,0.000000,0.000000,0.000000,0.000000,33,21.0,0.0,19,23,3
1,39.33,17.44,0.0,8.0,47.75,0.0,0.0,5.0,52.75,0.000000,0.000000,41.899602,-87.633308,33,21.0,0.0,19,18,0
2,8.93,4.83,28.0,22.0,14.75,0.0,0.0,0.0,14.75,41.874005,-87.663518,41.922761,-87.699155,33,21.0,0.0,19,19,1
3,20.93,13.29,76.0,0.0,34.00,0.0,0.0,6.0,40.00,41.980264,-87.913625,0.000000,0.000000,33,21.0,0.0,19,17,3
4,0.55,0.17,3.0,3.0,63.27,0.0,0.0,0.0,63.27,41.965812,-87.655879,41.965812,-87.655879,33,21.0,0.0,19,18,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5389589,3.27,0.57,6.0,6.0,4.75,2.0,0.0,1.0,8.25,41.944227,-87.655998,41.944227,-87.655998,37,6.0,0.0,2,31,1
5389590,5.90,0.85,32.0,32.0,5.75,0.0,0.0,1.0,6.75,41.880994,-87.632746,41.884987,-87.620993,37,6.0,0.0,2,17,1
5389591,1.72,0.31,3.0,3.0,4.00,0.0,0.0,1.0,5.00,41.965812,-87.655879,41.965812,-87.655879,37,6.0,0.0,2,31,1
5389592,8.33,1.58,7.0,7.0,11.00,10.0,0.0,0.0,21.00,41.922686,-87.649489,41.922686,-87.649489,37,6.0,0.0,2,17,2
5389593,8.98,1.85,32.0,28.0,11.48,0.0,0.0,0.0,11.48,41.878866,-87.625192,41.874005,-87.663518,37,6.0,0.0,2,19,1

In [ ]:
from skfuzzy.cluster import cmeans
df=df.drop(columns='cluster')
ddf=df.T
center, u, u0, d, jm, p, fpc = cmeans(ddf, m=2, c=19, error=0.005, maxiter=1000)
 
for i in u:
    label = np.argmax(u, axis=0)
df['cluster']=labels 
print(label)
df.to_csv('cluster_fuzzy.csv', index=False)

In [31]:
datapath = "data.csv"
dataX, labels = loadData(datapath)  # 读取数据

In [33]:

#dfx[['a','b','c']] = dfx[['a','b','c']].astype('float32')
dataX

array([['87.0', '12.0', '0.0'],
       ['61.0', '10.0', '0.0'],
       ['70.0', '6.0', '0.0'],
       ...,
       ['84.0', '16.0', '0.0'],
       ['29.0', '16.0', '0.0'],
       ['14.0', '7.0', '0.0']], dtype=object)

In [ ]:
from sklearn.mixture import GMM
gmm = GMM(n_components=4).fit(X)
labels = gmm.predict(X)